server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
      max-request-size: 100MB # 最大请求限制，因为一次请求可以有多个文件
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#
fdfs:
  so-timeout: 1501 #请求的超时时间
  connect-timeout: 601 #连接的超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.93.7.174:22122
cm:  #自己配置的
  upload:
    baseUrl: "http://47.93.7.174:8888/" #http://47.93.7.174:8888/group1/M00/00/00/rBHTxFyDKYSAdoMuAAKKYWPOKYk559.jpg
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp